### ISSUE TITLE
How can I access the WebUI mentioned in the README?

### ISSUE THREAD

**Issue by AiraNadih** [soulteary/RSS-Can#19]
I'm using the latest Docker image:

```
docker pull soulteary/rss-can:v0.3.6
docker run --rm -it -p 8888:8888 -v `pwd`/rules:/rules soulteary/rss-can:v0.3.6
```

I tried accessing the WebUI by opening `http://localhost:8888` in my browser, but it only displays "EOF".
Could someone please guide me on how to properly access the WebUI?

And here's the log info:

```
{"level":"info","msg":"version: v0.3.6 commit: 0a30618c2a098124043d4d16b8ac381df6f55455 build: 2023-04-27T15:00:49Z"}
{"level":"info","msg":"Load rules, count: 1"}
{"level":"info","msg":"RSS CAN has started 🚀"}
```

**Comment by soulteary** [comment]
Hi, @AiraNadih 

Some simple docker knowledge is involved here, 

You should not change the port inside the container **unless you specify a variable or parameter that adjusts** the application's startup port.

an example:

```bash
docker pull soulteary/rss-can:0.3.6
docker run --rm -it -p 8080:8080 -v `pwd`/rules:/rules soulteary/rss-can:v0.3.6
```

Its role is to associate external ports with internal ports, so you can adjust your command like this.

```bash
-p 8888:8080
```

Currently, if you particularly like this port number, or want to run the program directly on port 8888, you can adjust it like this.

```bash
docker run --rm -it -p 8888:8888 -e RSS_PORT=8888 -v `pwd`/rules:/rules soulteary/rss-can:v0.3.6
```
