### ISSUE TITLE
打成Linux可执行文件出现异常

### ISSUE THREAD

**Issue by zouopen** [soulteary/RSS-Can#34]
### 你遇到了什么样的麻烦？

<img width="1506" alt="image" src="https://github.com/soulteary/rss-can/assets/21697000/bac3c772-d7a0-4e6d-81c4-8d50611a740d">
请问一下为什么打包的时候会出现这个异常，打包命令如下：
CGO_ENABLED=1 GOOS=linux  GOARCH=amd64  CC=x86_64-linux-musl-gcc  CXX=x86_64-linux-musl-g++ go build -o main

在Linux环境下打包也是同样的问题。

### 如何复现这个问题？

使用该命令打包的时候会出现：
CGO_ENABLED=1 GOOS=linux  GOARCH=amd64  CC=x86_64-linux-musl-gcc  CXX=x86_64-linux-musl-g++ go build -o main

### 应用版本

Mac System 12.6
go version : 1.20

### 搜索

- [X] 在提交这个表格之前，我已经进行了相关问题搜索，没有找到相关的问题或解决方案。

**Comment by zouopen** [comment]
这个需要把v8go 版本降为0.8.0 才可以 具体来自这里 https://github.com/rogchap/v8go/issues/398 大概是gcc版本问题

**Comment by soulteary** [comment]
或许可以试试一律在容器内构建，构建完毕 cp 到本地使用，干净又卫生 :D @zouopen
